export const appActionTypes = {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_LOADING: 'CHANGE_LOADING',
    CHANGE_MODAL: 'CHANGE_MODAL',
    CHANGE_THEME: "CHANGE_THEME",
    CHANGE_SONG_SETTING: 'CHANGE_SONG_SETTING',
    CHANGE_SONG_PLAYING: 'CHANGE_SONG_PLAYING',
}

export const userActionTypes = {
    CHANGE_LOGIN: 'CHANGE_LOGIN', 
    LOGOUT: 'LOGOUT',
    CHANGE_USER_SIGNIN: 'CHANGE_USER_SIGNIN',
}