export const appActionTypes = {
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    CHANGE_LOADING: 'CHANGE_LOADING',
    CHANGE_MODAL: 'CHANGE_MODAL',
    CHANGE_THEME: "CHANGE_THEME",
    CHANGE_SONG: 'CHANGE_SONG',
}

export const userActionTypes = {
    CHANGE_LOGIN: 'CHANGE_LOGIN', 
    LOGOUT: 'LOGOUT'
}